export const Constant = {
  SignUpTitle: 'Welcome to Rappid Panic',
  SignUpDesc1: 'Enter your number to get started.',
  SignUpDesc2: `This will also be the number we call to\nconfirm responses, so make sure it’s one\nyou have readily available.`,
  PhoneNumber: 'Phone Number',
  Search: 'Search......',
  EnterNumber: 'Please enter number',
  ValidNumber: 'Please enter valid number',
  IAgree: 'I agree to the',
  TermsUse: 'Terms of Use',
  SelectTerms: 'Please Select Terms of Use',
  Next: 'Next',
  OTPTitle: 'Enter OTP',
  OneTimePin: 'A one-time pin has been sent to',
  EnterBelow: '. Please enter it below',
  Confirmed: 'Confirmed',
  ResendOTP: 'Resend OTP',
  Back: 'Back',
};
